'use client';
import { useEffect, useState } from 'react';
import { ApiError, apiFetch } from '../../lib/api';
type Invitation = { id: string; status: 'invited' | 'consented' | 'scheduled' | 'in_progress'; createdAt: string; job: { id: string; title: string; client: { id: string; name: string } } | null };
export function ScreeningInvitations() {
    const [items, setItems] = useState<Invitation[]>([]); const [error, setError] = useState(''); const [consentVersion, setConsentVersion] = useState('screen-v1');
    async function load() { try { setItems((await apiFetch<{ items: Invitation[] }>('/api/blinkfy/talent/screening/invitations')).items); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Screening invitations could not be loaded.'); } }
    useEffect(() => { void load(); }, []);
    async function consent(sessionId: string) { setError(''); try { const response = await apiFetch<{ session: { status: Invitation['status'] } }>(`/api/blinkfy/talent/screening/invitations/${sessionId}/consent`, { method: 'POST', body: JSON.stringify({ consentVersion }) }); setItems((current) => current.map((item) => item.id === sessionId ? { ...item, status: response.session.status } : item)); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Consent could not be recorded.'); } }
    async function withdraw(sessionId: string) { setError(''); try { await apiFetch(`/api/blinkfy/talent/screening/invitations/${sessionId}/withdraw`, { method: 'POST' }); setItems((current) => current.filter((item) => item.id !== sessionId)); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Consent could not be withdrawn.'); } }
    return <section aria-labelledby="screening-invitations-heading" className="mt-6 p-5 border border-border-strong rounded-[10px]"><h2 id="screening-invitations-heading">Screening invitations</h2><p>You decide whether to opt in. You can withdraw consent at any time.</p><label>Consent version <input value={consentVersion} onChange={(event) => setConsentVersion(event.target.value)} /></label>{error && <p role="alert">{error}</p>}{items.length === 0 ? <p>No active screening invitations.</p> : items.map((item) => <article key={item.id}><p><strong>{item.job?.title ?? 'Screening invitation'}</strong>{item.job?.client ? ` · ${item.job.client.name}` : ''} · status: {item.status}</p>{item.status === 'invited' && <button type="button" onClick={() => void consent(item.id)}>I consent to screening</button>} {item.status !== 'invited' && <button type="button" onClick={() => void withdraw(item.id)}>Withdraw screening consent</button>}</article>)}</section>;
}
