'use client';
import { useState } from 'react';
import { ApiError, apiFetch } from '../../lib/api';
export function WebhookSubscriptionPanel({ clientId }: { clientId: string }) {
    const [url, setUrl] = useState(''); const [secret, setSecret] = useState(''); const [message, setMessage] = useState('');
    async function save() { try { await apiFetch(`/api/blinkfy/clients/${clientId}/concierge/webhooks`, { method: 'PUT', body: JSON.stringify({ url, secret, events: ['candidate.responded', 'screening.completed', 'stage.changed'] }) }); setMessage('Webhook subscription saved. Deliveries require approval.'); } catch (caught) { setMessage(caught instanceof ApiError ? caught.message : 'Webhook subscription could not be saved.'); } }
    const [items, setItems] = useState<{ id: string; eventType: string; status: string }[]>([]);
    async function loadOutbox() { try { const result = await apiFetch<{ items: typeof items }>(`/api/blinkfy/clients/${clientId}/concierge/webhooks/outbox`); setItems(result.items); } catch (caught) { setMessage(caught instanceof ApiError ? caught.message : 'Webhook outbox could not be loaded.'); } }
    async function review(id: string, status: 'approved' | 'rejected') { try { const result = await apiFetch<{ item: typeof items[number] }>(`/api/blinkfy/clients/${clientId}/concierge/webhooks/outbox/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }); setItems((current) => current.map((item) => item.id === id ? result.item : item)); } catch (caught) { setMessage(caught instanceof ApiError ? caught.message : 'Webhook review could not be saved.'); } }
    return <section aria-label="Concierge webhook subscription"><h2>Webhook integration</h2><label>HTTPS endpoint<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://..." /></label><label>Signing secret<input value={secret} onChange={(event) => setSecret(event.target.value)} type="password" /></label><button type="button" onClick={save}>Save webhook</button><button type="button" onClick={() => void loadOutbox()}>Load pending deliveries</button>{message && <p role="status">{message}</p>}<small>Deliveries require approval. Only approved events are delivered; browser credentials and autonomous candidate outreach are not supported.</small>{items.length > 0 && <ul aria-label="Webhook delivery review">{items.map((item) => <li key={item.id}>{item.eventType} · {item.status} {item.status === 'pending_approval' && <><button type="button" onClick={() => void review(item.id, 'approved')}>Approve delivery</button><button type="button" onClick={() => void review(item.id, 'rejected')}>Reject delivery</button></>}</li>)}</ul>}</section>;
}
